/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package correo2;

import excel.ExcelReader;
import java.text.ParseException;
import java.util.Date;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import util.Utilsapp;
import java.io.File;
import java.text.Normalizer;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import mail.SendMail;

/**
 *
 * @author dmarcobo
 */
public class NewJPanel extends javax.swing.JPanel {
    
    private final ExcelReader exfile;
    private final String FMTFECHA = "dd/MM/yy";
    
    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
        
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(jTable2.getModel());
        jTable2.setRowSorter(sorter);
        
        TableRowSorter<TableModel> sorter1 = new TableRowSorter<>(jTable1.getModel());
        jTable1.setRowSorter(sorter1);
        
        exfile = new ExcelReader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        jLabel1.setText("Fichero");

        jTextField1.setText("C:\\SEGUIMIENTO_PETICIONES_20161007.xlsx");
        jTextField1.setName("rutaFichero"); // NOI18N
        jTextField1.setPreferredSize(new java.awt.Dimension(250, 22));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setText("Abrir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Procesar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Peticiones atrasadas");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Petición", "Estado", "Tipo", "Fecha", "Nombre", "Responsable"
            }
        ));
        jTable2.setMaximumSize(new java.awt.Dimension(32767, 32767));
        jTable2.setMinimumSize(new java.awt.Dimension(28, 32));
        jTable2.setName(""); // NOI18N
        jTable2.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(jTable2);

        jLabel3.setText("Peticiones que cumplen hoy");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Petición", "Estado", "Tipo", "Fecha", "Nombre", "Responsable"
            }
        ));
        jTable1.setMaximumSize(new java.awt.Dimension(32767, 32767));
        jTable1.setMinimumSize(new java.awt.Dimension(28, 32));
        jTable1.setName(""); // NOI18N
        jTable1.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
        );

        jButton3.setText("Enviar Correo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(10, 10, 10)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(314, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
          File selectedFile = fileChooser.getSelectedFile();
          jTextField1.setText(selectedFile.getPath());
        }       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            
            
            if (jTextField1.getText() == null || (jTextField1.getText() != null && jTextField1.getText().isEmpty())){
                JOptionPane.showMessageDialog(this, "Debes seleccionar un fichero");
                return;
            }
            
            exfile.readExcel(jTextField1.getText());

            List<ExcelReader.DesvioData> lista = exfile.getListadoDesvios();
            Date hoyHoras = new Date();
            Date hoy = Utilsapp.strToDate(Utilsapp.dateToStr(hoyHoras, FMTFECHA), FMTFECHA);

            System.out.println(Utilsapp.dateToStr(hoy, "dd/MM/yyyy hh:mm:ss") +  " Hay " +  lista.size());
            
            //System.out.println("******** Peticiones RETRASADAS: ");
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();

            lista.stream().filter((lista1) -> (lista1.getFechaFinAcuerdo() != null 
                    && lista1.getEstado().code() == ExcelReader.EstadoPet.EJECUCION.code())).forEach((lista1) -> {
                        //System.out.print(Utilsapp.dateToStr(lista.get(i).getFechaFinAcuerdo(), "dd/MM/yyyy hh:mm:ss"));
                        if (hoy.after(lista1.getFechaFinAcuerdo())) {
                            //System.out.println(" Retrasada");
                            model2.addRow(new Object[]{lista1.getPeticion(), lista1.getEstado().text(),
                                lista1.getTipo().text(),
                                Utilsapp.dateToStr(lista1.getFechaFinAcuerdo(), FMTFECHA),
                                lista1.getNombrePet(),
                                lista1.getActor()});
                        } else if (hoy.equals(lista1.getFechaFinAcuerdo())) {
                            //System.out.println(" Hoy");
                            model.addRow(new Object[]{lista1.getPeticion(), lista1.getEstado().text(),
                                lista1.getTipo().text(),
                                Utilsapp.dateToStr(lista1.getFechaFinAcuerdo(), FMTFECHA),
                                lista1.getNombrePet(),
                                lista1.getActor()});
                        }
                    });
            
            jLabel2.setText("Peticiones retrasadas: " + model2.getRowCount()); 
            jLabel3.setText("Peticiones que cumplen hoy: " + model.getRowCount()); 
            
        } catch (ParseException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    class ElemGroup{
        public String actor;
        public List <ExcelReader.DesvioData> grupo;
        
        public ElemGroup(){
            grupo = new ArrayList <>();
            actor = "";
        }
    }
            
            
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        
        
        List<ElemGroup> listaAgrupHoy = new ArrayList<>();
        List<ElemGroup> listaAgrupPasadas = new ArrayList<>();
        
        try {
            Date hoyHoras = new Date();
            Date hoy = Utilsapp.strToDate(Utilsapp.dateToStr(hoyHoras, FMTFECHA), FMTFECHA);
            List<ExcelReader.DesvioData> lista = exfile.getListadoDesvios();
            
            
            lista.stream().filter((lista1) -> (lista1.getFechaFinAcuerdo() != null 
                && lista1.getEstado().code() == ExcelReader.EstadoPet.EJECUCION.code())).forEach((lista1) -> {

                    //peticiones a entregar hoy
                    if (hoy.equals(lista1.getFechaFinAcuerdo())) {
                        boolean found = false;
                        int posFound = 0;
                        for (int i=0; i < listaAgrupHoy.size(); i++){
                            if (listaAgrupHoy.get(i).actor.equals(lista1.getActor()) ){
                                found = true;
                                posFound = i;
                            }
                        }
                        
                        if (!found){
                            ElemGroup elem = new ElemGroup();
                            elem.actor = lista1.getActor();
                            elem.grupo.add(lista1);
                            listaAgrupHoy.add(elem);
                        } else {
                            listaAgrupHoy.get(posFound).grupo.add(lista1);
                        }
                    }
                    
                    //peticiones a entregar hoy
                    if (hoy.after(lista1.getFechaFinAcuerdo())) {
                        boolean found = false;
                        int posFound = 0;
                        for (int i=0; i < listaAgrupPasadas.size(); i++){
                            if (listaAgrupPasadas.get(i).actor.equals(lista1.getActor()) ){
                                found = true;
                                posFound = i;
                            }
                        }
                        
                        if (!found){
                            ElemGroup elem = new ElemGroup();
                            elem.actor = lista1.getActor();
                            elem.grupo.add(lista1);
                            listaAgrupPasadas.add(elem);
                        } else {
                            listaAgrupPasadas.get(posFound).grupo.add(lista1);
                        }
                    }
            });
            
            generarCorreos(listaAgrupHoy, hoy, 
                    "Peticiones a entregar ",
                    " peticiones que cerrar hoy.", 
                    " Por favor, revísalas a continuación para que no aparezcas en sucesivos informes",
                    " petición que cerrar hoy.",
                    " Por favor, revísala a continuación para que no aparezcas en sucesivos informes");
            
            generarCorreos(listaAgrupPasadas, hoy,
                    "Peticiones desviadas ", 
                    " peticiones desviadas.", 
                    " Por favor, revísalas a continuación para que no aparezcas en sucesivos informes",
                    " petición desviada.",
                    " Por favor, revísala a continuación para que no aparezcas en sucesivos informes");
            
        } catch (Exception e){
            System.out.println(e.getMessage());
        }
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed
    
    /**
     * 
     * @param listaAgrupada
     * @param hoy 
     */
    private void generarCorreos(List<ElemGroup> listaAgrupada, Date hoy, String subject, String msg1, String msg2, String msg3, String msg4){
        SendMail mail = new SendMail();
               
        for (ElemGroup listaAgrupada1 : listaAgrupada) {
            String actor = listaAgrupada1.actor.split(" ")[0].toLowerCase();
            actor = actor.substring(0,1).toUpperCase() + actor.substring(1);
            StringBuilder htmlCode;
            htmlCode = new StringBuilder("<html><head>");
            
            htmlCode.append("<link rel=\"stylesheet\" href=\"/lib/w3.css\"><style>");
            
            
            htmlCode.append("table {\n"
                    + "    border-collapse: collapse;\n"
                    + "}");
            htmlCode.append("table, th, td {\n"
                    + "   border: 1px solid black;\n"
                    + "}");

            htmlCode.append("th, td {\n"
                    + "    padding: 15px;\n"
                    + "    text-align: left;\n"
                    + "}");
            htmlCode.append("tr:nth-child(even) {background-color: #f2f2f2}");

            htmlCode.append("th {\n"
                    + "    background-color: #99AE04;\n"
                    + "    color: white;\n"
                    + "}");
            
            htmlCode.append("</style></link>");
            
            htmlCode.append("<title></title></head><body>");
            htmlCode.append("Buenos días ").append(actor).append("<br/>");
            htmlCode.append("<br/><br/>");
            htmlCode.append("Tienes ").append(listaAgrupada1.grupo.size());
            if (listaAgrupada1.grupo.size() > 1) {
                htmlCode.append(msg1);
                htmlCode.append(msg2);
            } else {
                htmlCode.append(msg3);
                htmlCode.append(msg4);
            }
            htmlCode.append("<br/><br/>");
            htmlCode.append("<table><tr>");
            htmlCode.append("<th><b>Peticion</b></th>");
            htmlCode.append("<th><b>Tipo</b></th>");
            htmlCode.append("<th><b>Fecha entrega</b></th>");
            htmlCode.append("<th><b>Nombre</b></th>");
            htmlCode.append("</tr>");
            
            for (ExcelReader.DesvioData grupo : listaAgrupada1.grupo) {
                System.out.println(listaAgrupada1.actor);
                htmlCode.append("<tr><td>").append(grupo.getPeticion()).append("</td>");
                htmlCode.append("<td>").append(grupo.getTipo().text()).append("</td>");
                htmlCode.append("<td>").append(Utilsapp.dateToStr(grupo.getFechaFinAcuerdo(), FMTFECHA)).append("</td>");
                htmlCode.append("<td>").append(grupo.getNombrePet()).append("</td>");
                htmlCode.append("</tr>");
            }
            htmlCode.append("</table>");
            htmlCode.append("<br/><br/>Muchas gracias</body></html>");
            String[] nombreArr = listaAgrupada1.actor.split(" ");
            String tmp;
            String correo = "";
            for (int j=0; j < nombreArr.length; j++){
                tmp = nombreArr[j].toLowerCase();
                tmp = tmp.substring(0,1).toUpperCase() + tmp.substring(1);
                correo += (j > 0 ? "." : "") + tmp;
            }
            correo += "@everis.com";
            
            String normalized = Normalizer.normalize(correo, Normalizer.Form.NFD);
            String accentRemoved = normalized.replaceAll("\\p{InCombiningDiacriticalMarks}+", "");
            System.out.println("Enviando mail a: " + accentRemoved);
            
            mail.setTo(accentRemoved);
            mail.setSubject(subject + Utilsapp.dateToStr(hoy, FMTFECHA) + " " + correo);
            mail.setHtmlMessage(htmlCode.toString());
            mail.send();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
